### ISSUE TITLE
Adding options for Ultrawide screens

### ISSUE THREAD

**Issue by ruihildt** [emvaized/kde-snap-assist#12]
I was reading the Reddit Thread where one user spoke about using Ultrawide Kwin Script.

While having both working side by side is possible, it would be nice to have the possibility of displaying more combinations.
At least the 1/3 | 1/3 | 1/3 would be helpful.

Ideally, having all in one place would make it better in regard to dealing with shortcuts, but I can understand if that was out of scope.

**Comment by emvaized** [comment]
I def. would like to add 3-in-row layout support, with the ability to switch to 65/35 on the go. Stay tuned ;)

As for keyboard shortcuts – I would like to keep this script focused on a single purpose. There are plenty of other good KWin scripts which provide shortcuts for custom layouts, including the Ultrawide Windows which you mentioned, and the best solution for this script would be to simply enhance the list of supported layouts which it can handle.

**Comment by ruihildt** [comment]
> the best solution for this script would be to simply enhance the list of supported layouts which it can handle.

I would be perfectly happy if layouts proposed mirror the Ultrawide ones. :)

But at the same time, it would be cool if for example using the keyboard shortcuts launches snap assist, but this is a different feature request already.

**Comment by emvaized** [comment]
Well, I'm quite doubtful that Snap Assist could support **all** of possible layouts from Ultrawide Monitors, because it will require a lot of work, code lines, will possibly often cause false detections, while increasing the maintenance burder and the probability of unexpected bugs. 
At this point I'd prefer to stick to the most common and easily recognizable layouts, which should satisfy _most_ of the use cases, and for something more intricate you could always use the shortcuts and tools provided by other scripts.

> using the keyboard shortcuts launches snap assist
Well, it already does! Of course, if you use the shortcut for a supported layout, for example the default Super+arrow keys

**Comment by emvaized** [comment]
I just added test support for "3 columns" layout in the `dev` channel. 

If you'd like, you could test it and let me know how it works.
For this you'd need to:
- Delete current version of script and re-login to KDE Plasma
- Download [the code](https://github.com/emvaized/kde-snap-assist/tree/dev) as .zip (green "Code" button > "Download as ZIP"), and rename file to .kwinscript extension
- Use the "Install from file" button in System settings > Windows manager > KWin scripts
- Re-login to Plasma again (or restart KWin) to make sure the script is installed

**Comment by emvaized** [comment]
"3 columns" layout support is now added in version 1.3
