### ISSUE TITLE
Bug: exiting fullscreen triggers overlay

### ISSUE THREAD

**Issue by viv24pt** [emvaized/kde-snap-assist#15]
When a snapped application enters and exits fullscreen the snap assist overlay is triggered.

https://user-images.githubusercontent.com/44370330/184343511-0cf49767-a315-4303-ab5a-da19f17cfa4d.mp4

**Comment by emvaized** [comment]
I can see the reason why it happens. The script listens to move/resize end event, to check if the window was snapped (based on it's size and position). And this is what clearly happens on your demo — window gets resized and moved to position, which gets detected as "snapped" by the script, as it clearly fits the conditions.
So I can't see any bug or misbehavior in this. If you maximize/unmaximize the window from any other size and position (which could not be considered a snap zone), the assist will not show.

If you request to add a check to not show assist if move/resize event was caused by window unmaximize action — then, the move/resize event, which the script listens to, does not provide such information of what caused this event. Could be implemented as a workaround, to track window's size and position on every movement, and then on move end compare the current one to the last tracked one, to define if it was unmaximized. But I'm not sure if it's really worth the hassle.

**Comment by viv24pt** [comment]
I think there was a miscommunication. In the demo I was entering the fullscreen mode in a YouTube video, I did not maximise the window.   
I don't think that the overlay triggered by exiting a fullscreen video from a snapped window should be the intended behaviour.   
I agree that that the unmaximise action should be tracked but there should at least be an option to ignore actions from windows exiting the fullscreen state.

**Comment by emvaized** [comment]
I see what you mean now. Yeah, in this case it is indeed unintended behavior and could be quite annoying. 
I just applied a fix in the [dev](https://github.com/emvaized/kde-snap-assist/tree/dev) branch to test.

**Comment by emvaized** [comment]
The fix is now included in the new version 1.3 of the script, and on the `main` github branch
