### ISSUE TITLE
UI: remove the little sidebar 

### ISSUE THREAD

**Issue by developer91234** [emvaized/kde-snap-assist#26]
The sidebar on the right with the close and quarter button takes too much space from the window previews. The little buttons themselves are neither intuitive  nor convenient. (close button seems like "close window", tile button makes the whole UI hop around the screen etc.)

I therefore recommend to follow the canonical Windows UI and remove this thing. The close button isn't necessary since Esc is universally recognized. The quarter tile could be exported to a context menu, or - better - by simply draggin the thumbnail to the desired region.

Thank you for finally bringing this indispensable feature to KDE!

**Comment by emvaized** [comment]
The reasoning behind the "close" button is that it doesn't actually close the assist window, but rather freezes it and moves off-screen. If the user was able to close the assist window using the default titlebar, the script would've immediately stopped working, as it requires constantly opened instance of it's window.

So, it's rather a question of removing the close button at all – and I would rather leave it, because it's convenient and follows the principles of human design. Some users may be disoriented to not have the close button, because it's not visually obvious you can click on empty area around the grid to close the view. And relying only on "Escape" button to close the view would obviously be a terrible decision for a mouse-oriented utility.

The concept of this button actually did not come from the thin air – it emulates the same button in the "Overview" effect, included by default in Plasma – thus the another reason to keep it in the exact current form.

> The quarter tile could be exported to a context menu

The current nature of "Change layout" button is that it determines next possible layout based on the current one, so you currently can't simply list all the possible variants in the context menu. Thus, having a floating button is better in my opinion than having a context menu with one single entry – and it blends well with the already existing floating close button, the reasoning for which is explained above.

> close and quarter button takes too much space from the window preview

They actually don't take any screen space at all, as they're shown right above the horizontal padding on the right.

**Comment by emvaized** [comment]
Closing this now as a 'wontfix'

**Comment by developer91234** [comment]
There is a good reason why Windows snap assist UI is the way it is, I would reconsider.

> he concept of this button actually did not come from the thin air – it emulates the same button in the "Overview" effect

I don't see this button in the overview. There is no overview effect that has such a button, not on Mac, Windows, or Gnome.

**Comment by emvaized** [comment]
Hm, now that you mentioned, I also could not find any screenshots of windows overview with the close button, neither new effect or the old one ("present windows"). But I clearly had a picture in mind of the floating square button in the corner when I was designing it... Maybe some sort of Mandela effect? :D
