### ISSUE TITLE
Is It Possbile To Implement Snap Groups On Wayland?

### ISSUE THREAD

**Issue by semarainc** [emvaized/kde-snap-assist#29]
About the experimental feature snap groups, currently works for X11 only
Is it possible to make it work on Wayland?

Thanks

**Comment by emvaized** [comment]
Well, if it was that easy, I wouldn't have placed the "X11" label in the first place :) I already gave it a try to rework the feature so that it could function on Wayland, but had no luck yet.

**Comment by semarainc** [comment]
Ok, thank you for the explanation :D
i'm sorry if my question offended you

**Comment by semarainc** [comment]
Just curious, what makes this feature not yet applicable in wayland?
Thanks

**Comment by emvaized** [comment]
At first I thought that it's because of absence of `workspace.getClient()` method on Wayland, but replacing it with [this](https://github.com/emvaized/kde-snap-assist/blob/3ce8033af34ce3635773fb24feeb7dc38d4870e0/contents/ui/code/windows.js#L252) logically identical line does not help.

Then I suggested that the reason could be that `windowId` property itself is not reliable on Wayland to identify the windows, so I tried to rewrite the [snappedWindowGroups](https://github.com/emvaized/kde-snap-assist/blob/3ce8033af34ce3635773fb24feeb7dc38d4870e0/contents/ui/main.qml#L46) variable and all the related methods to store the client objects itself instead of only their `windowId`s, but it didn't help either.

**Comment by semarainc** [comment]
I guess kwin wayland currently is not capable of doing that :(
i think this also explained why exquisite cannot snap window when minimized?

Thank you for your detailed and helpful information :D

**Comment by emvaized** [comment]
I'm not sure. Maybe this issue will attract attention of someone more experienced with KWin Scripting and Wayland in particular, but for now I'm out of ideas of what else to try.

**Comment by emvaized** [comment]
Well, it turns out you can replace `windowId` everywhere with `internalId`, and after a few more changes here and there snap group features seems to be working on Wayland! As well as sorting by latest active window.

Would be glad if you could test the latest code from the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev).

**Comment by emvaized** [comment]
New patches are now merged to the `main` branch and included in 1.6 release. 
If you face some snap groups features not working under Wayland, please feel free to open a new issue.
