### ISSUE TITLE
Feature request: Filter tiled windows

### ISSUE THREAD

**Issue by nclarius** [emvaized/kde-snap-assist#4]
It would be nice if there was an option to only show windows that are not already snapped to some tile.

**Comment by emvaized** [comment]
I like this particular feature requests, because if we could track all windows snapped from the assist, all their relative groups, and then expose it somehow via DBus, it opens a door for a lot of possibilities. 

Additionally to filtering out already snapped windows inside the script, we can basically create a platform upon which a lot of interesting things can be built. Few examples:

- Modified Task switcher widget which could visually group snapped windows in shared tiles
- Modified Overview for windows and desktops which could group snapped windows
- Additional scripts, which would extend the assist, such as: 
  - minimize/restore snapped windows simultaneously;
  - move snapped windows with mouse as a group;
  - once one of the snapped windows gets closed, resize all the others to fill the freed area

So, a lot of things to think of!

**Comment by emvaized** [comment]
Well, it turns out there currently is [no way](https://bugs.kde.org/show_bug.cgi?id=445129) to communicate between scripts via DBus... 

Well, we still would be able to include some of these into the script itself. 
I just added test support for tracking snapped windows in the [dev](https://github.com/emvaized/kde-snap-assist/tree/dev) branch, as well as new options: 
- "Show previously snapped windows" under filter
- "Minimize/restore snapped windows together" and "Raise snapped windows together" under behavior

Will be glad if you could join testing!

**Comment by emvaized** [comment]
Option to filter out previously snapped windows was added now in version 1.4

**Comment by nclarius** [comment]
Nice! A further enhancement would be if it also filtered out windows that were tiled without the assistant, but this is already a good improvement.
