### ISSUE TITLE
Keyboard shortcut won't work after first use

### ISSUE THREAD

**Issue by DrunkenToast** [emvaized/kde-snap-assist#41]
When using shortcuts you might want to move the window multiple times with keyboard shortcuts. But after the first shortcut the window is not focused anymore and you can't move the window anymore.

**Comment by emvaized** [comment]
Maybe try increasing "Delay before showing the assist" in the script's settings? The default value is `100ms`

**Comment by DrunkenToast** [comment]
It's far from perfect, especially since the delay is from the first tile so if you move across screens you might have too little time and obviously setting it too high isn't especially nice either. But it is slightly better.

So maybe tiling multiple times should reset the timer?

I don't immediately see a good solution for the window itself not being focused anymore to allow the shortcuts to work either (besides maybe forwarding the actions to the last focused window if that's possible at all).

**Comment by emvaized** [comment]
This option was initially added for compatibility with so called "diagonal" snap shortcuts, e.g. `Meta`+`Left`+`Up`, and default value is more or less fine to have some time for hitting second shortcut after the initial one. If you need to hit more shortcuts to get window to the desired position, then the only option you have is to increase this threshold before the assist gets shown. Repositioning the initial window after assist is already shown is not technically possible, as we need to switch window focus to the assist's service window, so that it can access keyboard events in order to select second window with arrow keys.

**Comment by DrunkenToast** [comment]
Alright, well I'll consider this closed for time being. Thanks for the work on this script!

**Comment by manasan3010** [comment]
> Repositioning the initial window after assist is already shown is not technically possible, as we need to switch window focus to the assist's service window, so that it can access keyboard events in order to select second window with arrow keys.

When checking the keyboard events in the assist's service window, can't you check whether `Meta` key is still pressed or not?

PS: I am not a KWin dev
@emvaized
